### ISSUE TITLE
Wrong Season

### ISSUE THREAD

**Issue by nsalvato1996** [fewieden/MMM-NFL#15]
Hello,

I want to appreciate you for creating this. However, when loading the module the first attachment is what shows. The mode in the Node_helper.js is 'regular'. When it first loads up it will show the first game in the pre-season of 2018 the switches right back to "NFL UNDEFINED 2017". Is there anyway I can have it automatically switch between seasons? Any help would be appreciated, thank you in advance!

![capture](https://user-images.githubusercontent.com/15151576/36936042-b2186f54-1ecd-11e8-840c-4186e787db17.PNG)

**Comment by nsalvato1996** [comment]
Also, the scores are missing for the last played game in 2017

**Comment by fewieden** [comment]
- You saw the automatic switch between regular and post season performing already. On system start the regular season gets loaded and based on the data and some logic it might get switched to postseason, like in your case. It should automatically switch to the preseason on the 1st of June
- `NFL UNDEFINED 2017` is a known bug from here https://github.com/fewieden/MMM-NFL/issues/14#issuecomment-361471993, which I didn't had the time yet to fix.
- The score is a problem due to the used api didn't update the score of that match
- The bug only affects patriots fans though <img src="https://i.imgur.com/zCXMiU9.gif" width="22">

**Comment by cowboysdude** [comment]
I love this module..... I don't have a use for it after the SB so I don't see it being a priority to show preseason games in June......  End of July yes.

**Comment by nsalvato1996** [comment]
@fewieden Gotcha, thank you!
